--- #YAML:1.0
name:               XML-Bare
version:            0.43
abstract:           A minimal XML parser / schema checker / pretty-printer using C internally.
author:
    - David Helkowski <cpan@codechild.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:        0
    DynaLoader:  0
    Exporter:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
